name: Create Release

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +'%Y.%m.%d_%H-%M-%S')"

      - name: Create release file
        run: |
          echo "This is a sample release file" > release_notes.txt

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKENS }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          release_name: Release ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKENS }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_notes.txt
          asset_name: release_notes.txt
          asset_content_type: text/plain
